id: P122F73AE
initial_creation_type: input
source_metadata:
  title: Letters Series
  language: en
  description: 'Examples of official and personal correspondence:'
  volume:
    4b0f1321e76b4a92abc20a519fb913b9:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Advice
    b28ffba4802b46be917d1c589fd379e4:
      title: A Letter to the Fourteenth Dalai Lama, Supreme Victorious Guru of the
        Beings of the Three Realms
      parent: General
    827655281cad45e4931d3aff8ec6797e:
      title: Letter to Gyarong Khandro
      parent: General
created_at: '2022-03-01T04:10:27.888275'
last_modified_at: '2022-03-01T04:10:27.888283'
